# Generated by Django 3.2.10 on 2021-12-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nashville_sell_and_trade_api', '0002_savepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nashuser',
            name='bio',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='nashuser',
            name='picture',
            field=models.CharField(max_length=300),
        ),
    ]
